#!/usr/bin/env python3
"""
JobCopilot - OpenAPI Client & TypeScript Definitions Generator
Inspects FastAPI application schema and generates:
1. Versioned OpenAPI specification (`docs/openapi_v1.json`)
2. Typed JavaScript client runtime (`frontend/js/api_client.js`)
3. TypeScript ambient definitions (`frontend/js/api_client.d.ts`)
"""

import json
import sys
from pathlib import Path

# Add backend directory to sys.path
BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR / "backend"))
sys.path.insert(0, str(BASE_DIR))

from app.main import app  # noqa: E402


def generate_openapi_artifacts():
    print("🚀 Generating JobCopilot v1 OpenAPI specification and typed client...")

    # 1. Extract OpenAPI schema
    schema = app.openapi()
    v1_schema = dict(schema)
    v1_schema["info"] = {
        "title": "JobCopilot API v1",
        "version": "1.0.0",
        "description": "Version 1 of the JobCopilot Autonomous Career Operating System REST API."
    }

    # Filter paths for /api/v1
    v1_paths = {}
    for path, methods in schema.get("paths", {}).items():
        if path.startswith("/api/v1"):
            v1_paths[path] = methods

    v1_schema["paths"] = v1_paths

    # 2. Write docs/openapi_v1.json
    docs_dir = BASE_DIR / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    openapi_file = docs_dir / "openapi_v1.json"
    with open(openapi_file, "w", encoding="utf-8") as f:
        json.dump(v1_schema, f, indent=2)
    print(f"  ✓ Written: {openapi_file} ({len(v1_paths)} versioned endpoints)")

    # 3. Generate frontend/js/api_client.js
    frontend_js = BASE_DIR / "frontend" / "js"
    frontend_js.mkdir(parents=True, exist_ok=True)
    client_js_file = frontend_js / "api_client.js"

    js_code = '''/**
 * JobCopilot Official API Client (v1)
 * Auto-generated by scripts/generate_api_client.py. Do not edit manually.
 */

class JobCopilotClient {
  constructor(baseUrl = "/api/v1", token = null) {
    this.baseUrl = baseUrl;
    this.token = token;
  }

  setToken(token) {
    this.token = token;
  }

  async request(endpoint, method = "GET", body = null, customHeaders = {}) {
    const headers = {
      "Content-Type": "application/json",
      "Accept": "application/json",
      ...customHeaders
    };
    if (this.token) {
      headers["Authorization"] = `Bearer ${this.token}`;
    }

    const options = { method, headers };
    if (body && (method === "POST" || method === "PUT" || method === "PATCH")) {
      options.body = JSON.stringify(body);
    }

    const response = await fetch(`${this.baseUrl}${endpoint}`, options);
    if (!response.ok) {
      const errData = await response.json().catch(() => ({ detail: response.statusText }));
      const error = new Error(errData.detail || `Request failed with status ${response.status}`);
      error.status = response.status;
      error.data = errData;
      throw error;
    }
    return response.json();
  }

  // Auth endpoints
  auth = {
    login: (email, password) => this.request("/auth/login", "POST", { email, password }),
    register: (userData) => this.request("/auth/register", "POST", userData),
    refresh: (refreshToken) => this.request("/auth/refresh", "POST", { refresh_token: refreshToken }),
    me: () => this.request("/auth/me", "GET"),
    logout: () => this.request("/auth/logout", "POST"),
  };

  // Jobs endpoints
  jobs = {
    list: (status = null) => this.request(`/jobs${status ? `?status=${status}` : ""}`, "GET"),
    get: (jobId) => this.request(`/jobs/${jobId}`, "GET"),
    update: (jobId, data) => this.request(`/jobs/${jobId}`, "PATCH", data),
    apply: (jobId, dryRun = false) => this.request(`/jobs/${jobId}/apply?dry_run=${dryRun}`, "POST"),
  };

  // Analytics endpoints
  analytics = {
    getFunnel: () => this.request("/analytics/funnel", "GET"),
    getEvents: () => this.request("/analytics/events", "GET"),
    trackEvent: (eventData) => this.request("/analytics/events", "POST", eventData),
    getCohorts: (interval = "weekly") => this.request(`/analytics/cohorts?interval=${interval}`, "GET"),
    getConversions: () => this.request("/analytics/conversions", "GET"),
    getExperiments: () => this.request("/analytics/experiments", "GET"),
    createExperiment: (expData) => this.request("/analytics/experiments", "POST", expData),
    evaluateExperiment: (expId) => this.request(`/analytics/experiments/${expId}/evaluate`, "POST"),
  };
}

// Export for ES modules and browser global
if (typeof module !== "undefined" && module.exports) {
  module.exports = { JobCopilotClient };
} else if (typeof window !== "undefined") {
  window.JobCopilotClient = JobCopilotClient;
}
'''
    with open(client_js_file, "w", encoding="utf-8") as f:
        f.write(js_code)
    print(f"  ✓ Written: {client_js_file}")

    # 4. Generate frontend/js/api_client.d.ts
    client_dts_file = frontend_js / "api_client.d.ts"
    dts_code = '''/**
 * TypeScript definitions for JobCopilotClient v1
 */

export interface ApiResponse<T = any> {
  status: string;
  data?: T;
  [key: string]: any;
}

export declare class JobCopilotClient {
  baseUrl: string;
  token: string | null;

  constructor(baseUrl?: string, token?: string | null);
  setToken(token: string): void;
  request<T = any>(endpoint: string, method?: string, body?: any, customHeaders?: Record<string, string>): Promise<T>;

  auth: {
    login(email: string, password: string): Promise<ApiResponse>;
    register(userData: Record<string, any>): Promise<ApiResponse>;
    refresh(refreshToken: string): Promise<ApiResponse>;
    me(): Promise<ApiResponse>;
    logout(): Promise<ApiResponse>;
  };

  jobs: {
    list(status?: string | null): Promise<ApiResponse>;
    get(jobId: string): Promise<ApiResponse>;
    update(jobId: string, data: Record<string, any>): Promise<ApiResponse>;
    apply(jobId: string, dryRun?: boolean): Promise<ApiResponse>;
  };

  analytics: {
    getFunnel(): Promise<ApiResponse>;
    getEvents(): Promise<ApiResponse>;
    trackEvent(eventData: Record<string, any>): Promise<ApiResponse>;
    getCohorts(interval?: string): Promise<ApiResponse>;
    getConversions(): Promise<ApiResponse>;
    getExperiments(): Promise<ApiResponse>;
    createExperiment(expData: Record<string, any>): Promise<ApiResponse>;
    evaluateExperiment(expId: string): Promise<ApiResponse>;
  };
}
'''
    with open(client_dts_file, "w", encoding="utf-8") as f:
        f.write(dts_code)
    print(f"  ✓ Written: {client_dts_file}")

    print("✨ OpenAPI and client code generation complete!")


if __name__ == "__main__":
    generate_openapi_artifacts()
