/**
 * JobCopilot Official API Client (v1)
 * Auto-generated by scripts/generate_api_client.py. Do not edit manually.
 */

class JobCopilotClient {
  constructor(baseUrl = "/api/v1", token = null) {
    this.baseUrl = baseUrl;
    this.token = token;
  }

  setToken(token) {
    this.token = token;
  }

  async request(endpoint, method = "GET", body = null, customHeaders = {}) {
    const headers = {
      "Content-Type": "application/json",
      "Accept": "application/json",
      ...customHeaders
    };
    if (this.token) {
      headers["Authorization"] = `Bearer ${this.token}`;
    }

    const options = { method, headers };
    if (body && (method === "POST" || method === "PUT" || method === "PATCH")) {
      options.body = JSON.stringify(body);
    }

    const response = await fetch(`${this.baseUrl}${endpoint}`, options);
    if (!response.ok) {
      const errData = await response.json().catch(() => ({ detail: response.statusText }));
      const error = new Error(errData.detail || `Request failed with status ${response.status}`);
      error.status = response.status;
      error.data = errData;
      throw error;
    }
    return response.json();
  }

  // Auth endpoints
  auth = {
    login: (email, password) => this.request("/auth/login", "POST", { email, password }),
    register: (userData) => this.request("/auth/register", "POST", userData),
    refresh: (refreshToken) => this.request("/auth/refresh", "POST", { refresh_token: refreshToken }),
    me: () => this.request("/auth/me", "GET"),
    logout: () => this.request("/auth/logout", "POST"),
  };

  // Jobs endpoints
  jobs = {
    list: (status = null) => this.request(`/jobs${status ? `?status=${status}` : ""}`, "GET"),
    get: (jobId) => this.request(`/jobs/${jobId}`, "GET"),
    update: (jobId, data) => this.request(`/jobs/${jobId}`, "PATCH", data),
    apply: (jobId, dryRun = false) => this.request(`/jobs/${jobId}/apply?dry_run=${dryRun}`, "POST"),
  };

  // Analytics endpoints
  analytics = {
    getFunnel: () => this.request("/analytics/funnel", "GET"),
    getEvents: () => this.request("/analytics/events", "GET"),
    trackEvent: (eventData) => this.request("/analytics/events", "POST", eventData),
    getCohorts: (interval = "weekly") => this.request(`/analytics/cohorts?interval=${interval}`, "GET"),
    getConversions: () => this.request("/analytics/conversions", "GET"),
    getExperiments: () => this.request("/analytics/experiments", "GET"),
    createExperiment: (expData) => this.request("/analytics/experiments", "POST", expData),
    evaluateExperiment: (expId) => this.request(`/analytics/experiments/${expId}/evaluate`, "POST"),
  };
}

// Export for ES modules and browser global
if (typeof module !== "undefined" && module.exports) {
  module.exports = { JobCopilotClient };
} else if (typeof window !== "undefined") {
  window.JobCopilotClient = JobCopilotClient;
}
