// Interview prep: company brief, practice questions with scored feedback, and
// questions to ask the interviewer. All generated by the backend's interview studio.
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "./api";

export interface PracticeQuestion {
  id: string;
  category: string;
  question: string;
  key_concepts: string[];
  difficulty: string;
}

export interface Dossier {
  company: string;
  likely_tech_stack: string[];
  engineering_focus: string;
  common_interview_rounds: string[];
  key_preparation_tips: string[];
}

export interface AskThem {
  theme: string;
  question: string;
}

export interface AnswerFeedback {
  overall_score: number;
  rating: string;
  dimension_scores: Record<string, number>;
  matched_concepts: string[];
  missing_concepts: string[];
  has_metrics: boolean;
  feedback: string;
}

const qs = (params: Record<string, string>) => new URLSearchParams(params).toString();

export function usePracticeQuestions(role: string) {
  return useQuery({
    queryKey: ["prep", "questions", role],
    enabled: Boolean(role),
    queryFn: async () => (await api<{ questions: PracticeQuestion[] }>(`/interview/questions?${qs({ role })}`)).questions,
    staleTime: Infinity,
  });
}

export function useDossier(company: string, role: string) {
  return useQuery({
    queryKey: ["prep", "dossier", company, role],
    enabled: Boolean(company),
    queryFn: async () => (await api<{ dossier: Dossier }>(`/interview/dossier?${qs({ company, role })}`)).dossier,
    staleTime: Infinity,
  });
}

export function useAskThem(company: string, role: string) {
  return useQuery({
    queryKey: ["prep", "reverse", company, role],
    enabled: Boolean(company),
    queryFn: async () => (await api<{ questions: AskThem[] }>(`/interview/reverse-questions?${qs({ company, role })}`)).questions,
    staleTime: Infinity,
  });
}

export function useAnswerFeedback() {
  return useMutation({
    mutationFn: (input: { question: string; candidate_answer: string; key_concepts: string[] }) =>
      api<{ evaluation: AnswerFeedback }>("/interview/evaluate", { method: "POST", body: input }),
  });
}

/** Drops the decorative emoji the backend puts in front of themes and ratings. */
export function plainText(s: string): string {
  return s.replace(/^[^\p{L}\p{N}]+/u, "").replace(/\s*[^\p{L}\p{N}).!?]+$/u, "").trim();
}

/** Readable names for the backend's STAR scoring dimensions. */
export const DIMENSION_LABELS: Record<string, string> = {
  situation: "Context",
  action: "What you did",
  result: "Result",
  delivery: "Delivery",
};
